### ISSUE TITLE
error when running main.py

### ISSUE THREAD

**Issue by nakumiayumu144** [HRNPH/AIwaifu#2]
![image](https://user-images.githubusercontent.com/127565115/228802448-a809550d-e23b-4c35-831f-9c2cbe1f9ca9.png)

**Comment by HRNPH** [comment]
will fix this today Lemme check

**Comment by HRNPH** [comment]
according to this
https://techoverflow.net/2021/02/06/how-to-fix-python-websocket-typeerror-__init__-missing-3-required-positional-arguments-environ-socket-and-rfile/
I think it's either your dependencies is wrong or my requirements are broken

since running this locally in my computer work flawlessly please try this and notice me if it's working or not:
```bash
pip uninstall websocket
pip install websocket-client
```

**Comment by nakumiayumu144** [comment]
thanks its worked
